// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ports/download_job_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "gin-quickstart/internal/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDownloadJobRepository is a mock of DownloadJobRepository interface.
type MockDownloadJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadJobRepositoryMockRecorder
}

// MockDownloadJobRepositoryMockRecorder is the mock recorder for MockDownloadJobRepository.
type MockDownloadJobRepositoryMockRecorder struct {
	mock *MockDownloadJobRepository
}

// NewMockDownloadJobRepository creates a new mock instance.
func NewMockDownloadJobRepository(ctrl *gomock.Controller) *MockDownloadJobRepository {
	mock := &MockDownloadJobRepository{ctrl: ctrl}
	mock.recorder = &MockDownloadJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadJobRepository) EXPECT() *MockDownloadJobRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDownloadJobRepository) Create(ctx context.Context, job entity.DownloadJob) (entity.DownloadJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(entity.DownloadJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDownloadJobRepositoryMockRecorder) Create(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDownloadJobRepository)(nil).Create), ctx, job)
}

// Delete mocks base method.
func (m *MockDownloadJobRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDownloadJobRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDownloadJobRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockDownloadJobRepository) Get(ctx context.Context, id string) (entity.DownloadJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.DownloadJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDownloadJobRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDownloadJobRepository)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockDownloadJobRepository) Update(ctx context.Context, job entity.DownloadJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDownloadJobRepositoryMockRecorder) Update(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDownloadJobRepository)(nil).Update), ctx, job)
}
